title: Luiz Tech Notes
description: Repositório de Estudos em Tecnologias Modernas
baseurl: /luiz-tech-notes
url: https://luiz-silva19.github.io

# Theme
theme: just-the-docs

# Logo e Favicon
logo: "/assets/images/logo.png"
favicon_ico: "/assets/favicon.ico"

# Esquema de cores
color_scheme: light

# Configurações de Busca
search_enabled: true
search.heading_level: 2
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 5

# Breadcrumbs
breadcrumbs:
  root_label: Home
  separator: "/"

# Configurações de Layout
aux_links:
  GitHub:
    - https://github.com/Luiz-Silva19/luiz-tech-notes

aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2025 Luiz Silva. Licensed under MIT License."

# Plugins
plugins:
  - search
  - jekyll-seo-tag

# Configurações SEO
title_separator: "|"
author: Luiz Silva
email: seu-email@example.com

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
