version: "3.9"

services:
  jekyll:
    image: jekyll/jekyll:4
    container_name: luiz-tech-notes
    command: jekyll serve --watch --force_polling --baseurl "/luiz-tech-notes"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
